### PR TITLE
Update all the things

### PR DESCRIPTION
**Pull request by schlan**
Update plugins and stuff ...

:chicken: :chicken: :chicken: :chicken: :chicken: :chicken: :chicken: :chicken:

### CODE REVIEW

**Comment by schlan** [comment]
:hatching_chick: :hatched_chick: :baby_chick: :chicken:

**Comment by MrGradient** [comment]
@schlan wow, this looks like an cool update, thx cooperate me

**Comment by makubi** [comment]
Nice work!

**Comment by makubi** [comment]
:D

**Pull request merged**
